# Generated by Django 4.2.4 on 2023-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partnername', models.CharField(max_length=100)),
                ('partnerkey', models.CharField(max_length=100)),
                ('dns', models.CharField(max_length=16)),
                ('company_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=100)),
                ('sitekey', models.CharField(max_length=100)),
                ('dns', models.CharField(max_length=16)),
                ('company_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
    ]
