# Generated by Django 4.2.4 on 2023-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
