# Generated by Django 4.2.4 on 2023-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partnername', models.CharField(max_length=100)),
                ('partnerkey', models.CharField(max_length=100)),
            ],
        ),
    ]
