# Generated by Django 4.2.4 on 2023-09-20 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApps', '0010_alter_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[['read', 'Read'], ['write', 'Write']], max_length=20), size=8), size=None),
        ),
    ]
